### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#60]

**Comment by bpetetot** [comment]
Convert docgen model to markdown

**Comment by bpetetot** [comment]
- [x] create documentation endpoints (for markdown) : #91 
- [x] create file saving endpoints (for README file) : #91 
- [x] add a router to manage navigation to the documentation screen : #94 
- [ ] save readme file endpoint
- [x] documentation screen
- [ ] format documentation
- [ ] add a documentation editor in gui
- [ ] make tests
